quarkus.devservices.enabled=false
quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.jdbc.url=jdbc:h2:file:./country_db
quarkus.datasource.username=sa
quarkus.rest-client.api-key.follow-redirects=true
quarkus.rest-client.country-api.url=https://api.restcountries.com
quarkus.cxf.client.countryClient.wsdl=classpath:wsdl/CountryInfoService.wsdl
quarkus.cxf.client.countryClient.client-endpoint-url=http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso
quarkus.cache.enabled=truequarkus.cache.caffeine.country-list.expire-after-write=1H
quarkus.cache.caffeine.country-list.expire-after-write=1H
quarkus.cache.caffeine.rest-country-list.expire-after-write=1H
%test.quarkus.rest-client.country-api.url=${quarkus.wiremock.devservices.url}
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.datasource.jdbc.url=jdbc:h2:file:./test_country_db
%test.api.external.auth-token=test-token-12345
API_AUTH_TOKEN=rc_live_cb64e33accc948c0a7b1a04f7c4a957a
%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
