quarkus.devservices.enabled=false
quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.jdbc.url=jdbc:h2:file:./country_db
quarkus.datasource.username=sa
quarkus.rest-client.api-key.follow-redirects=true
api.external.auth-token =rc_live_cb64e33accc948c0a7b1a04f7c4a957a
quarkus.cxf.client.countryClient.wsdl=classpath:wsdl/CountryInfoService.wsdl
quarkus.cxf.client.countryClient.client-endpoint-url=http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso
quarkus.cache.enabled=truequarkus.cache.caffeine.countries-list.expire-after-write=1H
quarkus.cache.caffeine.country-list.expire-after-write=1H
quarkus.cache.caffeine.rest-country-list.expire-after-write=1H
